Add pip installation fallback for self-hosted runner

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -34,6 +34,8 @@ jobs:
 
     - name: Install dependencies
       run: |
+        python3 --version
+        which pip3 || (echo "pip3 not found, installing pip..." && python3 -m ensurepip --upgrade || curl https://bootstrap.pypa.io/get-pip.py | python3)
         python3 -m pip install --upgrade pip
         python3 -m pip install -r requirements_dev.txt
         python3 -m pip install -r requirements_style.txt
@@ -66,6 +68,7 @@ jobs:
 
     - name: Install style dependencies
       run: |
+        which pip3 || (echo "pip3 not found, installing pip..." && python3 -m ensurepip --upgrade || curl https://bootstrap.pypa.io/get-pip.py | python3)
         python3 -m pip install --upgrade pip
         python3 -m pip install -r requirements_style.txt
 
@@ -141,6 +144,7 @@ jobs:
 
     - name: Install dependencies
       run: |
+        which pip3 || (echo "pip3 not found, installing pip..." && python3 -m ensurepip --upgrade || curl https://bootstrap.pypa.io/get-pip.py | python3)
         python3 -m pip install --upgrade pip
         python3 -m pip install -r requirements_dev.txt
 
